displayName=Pigeon
author=Bradl, Dink contributors
build=standard
description=Profile-based Discord-compatible webhook notifications for RuneLite events.
tags=loot,logger,collection,pet,death,xp,level,notifications,discord,webhook,profiles,speedrun,diary,combat-achievements,barbarian-assault
plugins=pigeon.PigeonPlugin
version=0.1.2
